version: '2'
services:
    app:
        build: .
        volumes:
            - .:/app
            - ./tmp:/tmp/:rw
        command: uwsgi --ini config/uwsgi.ini
        ports:
            - 5000:5000